### ISSUE TITLE
Integrate TTS log with main log

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-tasks#103]
@alexbernier Do you recall why it was decided to have a separate log file for the TTS processing?

For simplicity I'd like to integrate it with the main log.

**Comment by alexbernier** [comment]
@bertfrees Hi Bert, Sorry for this late reply. Because main logs are in text, it's hard to find what goes wrong in the context of multi-threading processing. A TTS log is an XML file specific to a job: it's easy to parse and to know, for example, which sentences were not processed by a TTS engine (and wheter a fallback TTS engine was selected).

Alex

**Comment by bertfrees** [comment]
We should at least have the error messages also in the main log because a job might never finish (e.g. due to a bug) so that the TTS log would not be available.
