### ISSUE TITLE
Initial version of EPUB 3 to DAISY 2.02

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#16]
@josteinaj can you create PRs based on your existing branches ?

**Comment by josteinaj** [comment]
The branch includes a EPUB3 Validator script as well as a DAISY 2.02 Validator script. The EPUB3 to DAISY 2.02 script validates the input and output. The EPUB3 Validator depends on the epubcheck-adapter, which does not work with the lastest release of epubcheck.

Should I wait for the next epubcheck release, or should I remove the epub3 validator script temporarily?

**Comment by rdeltour** [comment]
> Should I wait for the next epubcheck release, or should I remove the epub3 validator script temporarily?

Can you extract both validation sides into independent validators for the moment ? It would be more consistent with other scripts.

**Comment by josteinaj** [comment]
You mean don't validate input/output?

**Comment by rdeltour** [comment]
> You mean don't validate input/output?

Yeah. What do you think ?
Ideally the transformation should accept slightly invalid input (to a reasonable extent), and it should guarantee that the output is valid without checking with a validator.

Or what about make validation an option instead ? If you do that, I'd vote for disabling the EPUB validator until next release of EpubCheck.

**Comment by josteinaj** [comment]
I agree output validation could be skipped, and is mostly to catch bugs in the script and alert the user of bad output. I guess we could suppress the validation report if the result is valid. Note that the output fileset should be available even though the result is invalid.

To guarantee valid output, the input must be predictable. I would think that it's better to get a validation error on the input fileset rather than getting some XProc or XSLT error, and I suppose converters are easier to implement as well if they can assume that the input is valid.

Slightly invalid input (or terribly invalid input) could be fixed with "fixer" steps; `px:epub3-fixer`, `px:daisy3-fixer`, `px:daisy202-fixer`, etc.. These could be exposed as scripts as well.

It should be fairly easy to remove the input/output validation if you think it's best. It's just a matter of skipping the validation steps and disabling the report status and html ports.

**Comment by josteinaj** [comment]
I've separated the DAISY 2.02 Validator into a separate PR: daisy/pipeline-scripts#49

I'll strip EPUB3 to DAISY 2.02 of its validator dependencies and create a PR for that as well.

As for the EPUB3 Validator, I suppose I'll wait until epubcheck v4 is released, and then create a PR for that as well.

**Comment by josteinaj** [comment]
EPUB3 to DAISY 2.02 PR: daisy/pipeline-scripts#50
