### ISSUE TITLE
DTBook to EPUB 3 + MO with TTS narration

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#17]

**Comment by rom1mouret** [comment]
I suggest to merge the PRs in that order

#### 1. NLP

Merge branch `prepare-for-epub3` #12 of pipeline-mod-nlp.
Changes in the BOM:

``` xml
<dependency>
     <groupId>org.daisy.pipeline.modules</groupId>
     <artifactId>nlp-break-detection</artifactId>
     <version>1.0.1-SNAPSHOT</version> <!-- before: 1.0.0 -->
     </dependency>
<dependency>
     <groupId>org.daisy.pipeline.modules</groupId>
     <artifactId>html-break-detection</artifactId>
     <version>1.0.1-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
```

It should not break anything.

#### 2. Running multiple TTS steps

This is optional with the current workflow.
Merge branch `audio-conflicts` #22 of pipeline-mod-tts

Changes in the BOM:

``` xml
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>ssml-to-audio</artifactId>
    <version>1.0.1-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
```

It should not break anything

#### 3. Prevent out-of-memory exceptions

Merge branch `memfriendly` #18 of pipeline-mod-tts

Changes in the BOM:

``` xml
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>text-to-ssml</artifactId>
    <version>1.0.1-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
```

It should not break anything

#### 4. New audio encoder interface

The new interface expects a list of audio buffers rather than a big byte array. Lame has been changed accordingly.

Merge branch `stream` #11 of pipeline-mod-audio

Changes in the BOM:

``` xml
<dependency>
   <groupId>org.daisy.pipeline.modules</groupId>
   <artifactId>audio-common</artifactId>
   <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
<dependency>
   <groupId>org.daisy.pipeline.modules</groupId>
   <artifactId>audio-encoder-lame</artifactId>
   <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
```

Audio-common and audio-encoder-lame's versions must be changed in their POMs too.

The TTS won't work before branch `fast` is merged (unless pipeline-assembly explicitly uses the 1.0.0 versions).

#### 5. New internal TTS algorithms.

The threading mechanism and the memory management are changed. The new interface of AudioEncoder is employed. Gender can be used as a new criterion to select voices. SSML adapters are written in XSLT. A lot of refactoring and new error messages.
- merge branch `fast` #15 of pipeline-mod-tts
- merge branch `gender` #21 of pipeline-mod-tts

So far they don't pass the Travis tests because `stream` is not merged. Hopefully, they will pass them after but I offer no guarantee.

Changes in the BOM:

``` xml
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>ssml-to-audio</artifactId>
    <version>1.0.2-SNAPSHOT</version> <!-- before: 1.0.1-SNAPSHOT -->
</dependency>
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>tts-adapter-acapela</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>tts-adapter-attnative</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0-SNAPSHOT -->
</dependency>
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>tts-adapter-espeak</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>tts-adapter-osx</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>tts-adapter-sapinative</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>tts-common</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>

```

Versions in POMs must be changed too.

At this point, I believe dtbook-to-daisy3 should still work.

#### 6. Rebase

Because of conflicts on the class VoiceInfo, the next merge cannot be performed without a rebase.
So I will take care of it and rebase branch `move-css` #24 of pipeline-mod-tts.

#### 7. New general workflow

Merge branch `move-css` #24 of pipeline-mod-tts. It improves the CSS inlining and makes the changes so that the inlining can be invoked from outside the TTS cycle. The NLP and TTS is now expected to be called on the output documents. Furthermore, the TTS steps now take as input a config file, instead of the current string options.

After that, dtbook-to-daiy3 will no longer work.

Changes in the BOM:

``` xml
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>css-speech</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>dtbook-to-ssml</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>dtbook-tts</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>epub3-to-ssml</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>ssml-to-audio</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.1-SNAPSHOT -->
</dependency>
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>text-to-ssml</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.1-SNAPSHOT -->
</dependency>
```

Currently, it doesn't pass the Travis tests because the BOM tts-common's version is 1.0.0 whereas the POM's version is 1.0.1-SNAPSHOT.

#### 8. dtbook-to-daisy3

Dtbook-to-daisy3 is broken. Merge branch `tts-new-workflow` #48 of pipeline-scripts

There is an API break (in case dtbook-to-daisy3 is called by another script).
Changes in the POM:

``` xml
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>dtbook-to-daisy3</artifactId>
    <version>2.0.0-SNAPSHOT</version> <!-- before: 1.0.0 -->
</dependency>
```

#### 9. EPUB3 workflow
- Merge branch `epub3-tts` #23 of pipeline-mod-tts
- Merge branch `epub3-tts` #47 of pipeline-assembly

There might be a conflict on this one, because of `move-css`. In that case, I'll do a rebase.

Changes in the BOM:

``` xml
<dependency>
    <groupId>org.daisy.pipeline.modules</groupId>
    <artifactId>epub3-to-ssml</artifactId>
    <version>3.0.0-SNAPSHOT</version> <!-- before: 2.0.0-SNAPSHOT -->
</dependency>
```

#### 9. Language translation

Merge branch `html-chapter-lang` #52 of pipeline-scripts.
Otherwise the wrong voices and the wrong lexers will be chosen for non-English documents.

#### 10. Pre-requisites for EPUB3 with TTS

Merge branch `epub3-with-tts` #61 of pipeline-script-utils.

It is based on branch `move-create-mo` that allows us to call the mo functions in zedai-to-epub3.

Once `epub3-with-tts` is merged, `move-create-mo` can be closed.

It should not break anything.

#### 11. dtbook-to-epub3 and zedai-to-epub3

Merge branch `epub3-with-tts` #53 of pipeline-scripts

This is a light version. I had to set to 'false' the 'assert-valid' option of upgrade-dtbook because the TTS-related attributes are not compliant. But the validation is done right after anyway, with the TTS attributes removed.

#### 12. Cleaning

Merge branch `move-create-mo` #44 of pipeline-scripts

---

There are some other PRs, but they do not concern dtbook-to-epub3 or any features broken by the PRs.

The 'config file' feature is not yet finished. It's too messy right now to finish it. But it must be done for the next release. Yet another change of the AudioEncoder interface is needed too, so as to pass runtime options to encoders.

**Comment by rdeltour** [comment]
I'm done merging all the PRs, but haven't tested yet.

Note that some BoM versions ended up different that what you suggested in the above comment, but that shouldn't affect the result.

Thanks for the detailed walkthrough!
