### ISSUE TITLE
Improved image descriptions

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#3]
- [x] DIAGRAM content is converted to HTML image descriptions
- [x] make sure that image descriptions follow the recommended guidelines

**Comment by danielweck** [comment]
**FYI**
Tobi currently exports image descriptions as follows:

1) Full DIAGRAM XML (ZedAI syntax). In DAISY3, this file is linked from epub:describedAt (tentative implementation from a while ago), however this is not supported by any player. In EPUB3, the XML is just referenced from the OPF as a manifest item, but is not actually used anywhere. Each image has its descriptions stored in a subfolder with the same filename.

2) in DAISY3, we "inject" producer notes in the original DTBOOK (immediately under the annotated image), to include textual descriptions (longdesc, simplifiedLanguage, etc. we do not include alternate tactile / simplified images). We use the "code" element to wrap the potential Zed markup present in the description's textual content (tentative implementation due to lack of player support). We also synchronise the audio descriptions via SMIL (this is a feature extension specific to Tobi, not a standard DIAGRAM feature).

3) in EPUB3, we add the longdesc attribute, which points to a specially-crafted XHTML5 document that   contains only the DIAGRAM "longdesc". Users can opt-in to add the aria:describedat and aria:describedby attributes (the latter requires an iframe to be injected at the end of the host HTML body), both attributes reference (directly or indirectly) a specially-crafted XHTML5 document that contains all the authored DIAGRAM description types (text, alternate images, synchronised audio). We use a CSS stylesheet that helps visualise the various DIAGRAM "fields", and our markup is semantically-annotated so that future reading system implementations can show/hide content that is relevant to a particular class of users (as per the DIAGRAM types).

4) one possible future direction is to use EPUB3's linear="no" spine items, so that full SMIL synchronisation can be used in XHTML5 content documents that contain DIAGRAM descriptions. Right now, we just use the HTML5 "audio" element, inlined next to the textual or image element it is associated with.

**Comment by rdeltour** [comment]
Great, thanks for the info @danielweck !

**Comment by josteinaj** [comment]
see also: daisy/pipeline-issues#299
