### ISSUE TITLE
Update Calabash and Saxon to newer versions

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-tasks#85]

**Comment by bertfrees** [comment]
Including for xproc-engine-calabash.

**Comment by bertfrees** [comment]
At first I upgraded Saxon to 9.6 but had to revert to 9.5 because some XSLTs took forever. I'm now going to try with 9.7 and if that doesn't solve the issue I'll just make a PR with the Calabash update only.

**Comment by bertfrees** [comment]
See PRs:
- [x] https://github.com/daisy/pipeline-framework/pull/117
- [x] https://github.com/daisy/xproc-maven-plugin/pull/21
- [x] https://github.com/daisy/pipeline-build-utils/pull/36
- [x] https://github.com/daisy/pipeline-modules-common/pull/100
- [x] https://github.com/daisy/pipeline-mod-braille/pull/150

**Comment by bertfrees** [comment]
See https://github.com/daisy/xproc-maven-plugin/pull/21

**Comment by bertfrees** [comment]
@josteinaj The following branches from you can be deleted because they have been incorporated or replaced by other branches.

- [x] https://github.com/daisy/xproc-maven-plugin/compare/master...calabash-1.1.9-96
- [x] https://github.com/daisy/pipeline-mod-braille/compare/7bdd6f5...saxon-9.6.0-9
- [x] https://github.com/daisy/pipeline-modules-common/compare/master...calabash-1.1.9-96
- [x] https://github.com/daisy/pipeline-framework/compare/03138e8...job-messages-java.saxon96
- [x] https://github.com/daisy/pipeline-build-utils/compare/master...saxon96
- [x] https://github.com/daisy/pipeline-scripts-utils/compare/master...saxon-9.6.0-9
- [x] https://github.com/daisy/pipeline-scripts/compare/master...saxon-9.6.0-9

I'll leave the deleting up to you just in case you wanted to keep something.

The following branches should not be deleted yet:

- https://github.com/daisy/osgi-libs/compare/master...saxon96
- https://github.com/daisy/pipeline-assembly/compare/master...saxon-calabash-upgrade-wip

**Comment by bertfrees** [comment]
> At first I upgraded Saxon to 9.6 but had to revert to 9.5 because some XSLTs took forever.

I have tried 9.7 but it didn't solve the issue. I haven't looked into it much further.

**Comment by bertfrees** [comment]
Branches for Saxon 9.6 update (for later):
- https://github.com/daisy/osgi-libs/compare/master...saxon96
- https://github.com/daisy/xmlcalabash1/tree/org.daisy.libs-96
- https://github.com/daisy/pipeline-framework/compare/calabash-1.1.9...saxon-9.6
- https://github.com/daisy/pipeline-build-utils/compare/calabash-1.1.9...xprocspec-1.2.0
- https://github.com/daisy/pipeline-mod-braille/compare/calabash-1.1.9...saxon-9.6

Branches for Saxon 9.7 and Calabash 1.1.15 update (for later):
- https://github.com/daisy/osgi-libs/compare/master...saxon97
- https://github.com/daisy/xmlcalabash1/tree/org.daisy.libs-1.1.5-97
- https://github.com/daisy/pipeline-framework/compare/saxon-9.6...saxon-9.7
- https://github.com/daisy/pipeline-mod-braille/compare/saxon-9.6...saxon-9.7
